
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Apr 09 09:54:36 CST 2021
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 6;
  public static final int PR_BOOLEAN = 19;
  public static final int CADENA = 24;
  public static final int IGUAL = 11;
  public static final int DECIMAL = 22;
  public static final int DIVIDIDO = 8;
  public static final int PR_FOR = 16;
  public static final int PARIZQ = 3;
  public static final int PARDER = 4;
  public static final int UMENOS = 23;
  public static final int MENORQ = 10;
  public static final int POR = 7;
  public static final int PR_PRINT = 15;
  public static final int PR_IF = 13;
  public static final int MAYORQ = 9;
  public static final int EOF = 0;
  public static final int DIFERENTE = 12;
  public static final int error = 1;
  public static final int PR_STRING = 20;
  public static final int ENTERO = 21;
  public static final int PR_NUMBER = 18;
  public static final int PR_WHILE = 17;
  public static final int MAS = 5;
  public static final int PR_ELSE = 14;
  public static final int PTCOMA = 2;
}

